### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by SanjivanM**
Capitalized your name in cesium.asm
indents in readme
Added the fact that Cesium can be uninstalled in Cesium itself...

### CODE REVIEW

**Comment by mateoconlechuga** [comment]
NO CAPITALS IN SOURCE CODE PLEASE :D
Please fix it though.

**Comment by mateoconlechuga** [comment]
Meh I'll do it myself. Thanks! :)

**Comment by adriweb** [comment]
But... sentences first letter and names should though, at least :P

**Comment by mateoconlechuga** [comment]
No capitals in any source code ever :P

**Pull request merged**
